# lorebox.yml
# The singular and only config file for lorebox server

# Root directory for storing repositories
# Please use an absolute path here for predictability purposes
root: "/lorebox"

# The name of your box. Can be anything. You can put your domain in here, e.g.
# name: "box.bob.net"
name: "i-didnt-edit-example-config"

# Listen for incoming connections at :8081. This port is behind reverse
# proxy of Caddy. Notice that :8081 is not published by docker-compose, hence is
# only accessible for Caddy
listen: ":8081"

# Options:
# all -- need auth for any action
# new -- need auth only for fetching new (uncached) repos
# none -- no auth. Dangerous, don't use unless you know what you are doing
auth: new

# Time syntax:
# Xd, Xh, Xm, Xs -- X days, hours, minutes, seconds
timeouts:
  git:
    regular: 5m
    clone: 30m
  refresh:
    default: 12h
    max: 20d
    # Refresh is randomized within these margins
    jitter:
      min: 20m
      max: 50m

disk:
  # Maximum disk space lorebox will use
  # Syntax: XG, XM, XK, X -- X gigabytes, megabytes, kilobytes, bytes
  max: 10G
  # What to do if maximum disk usage is reached. Possible options:
  # lru -- enforce Least Recently Used eviction policy
  # deny -- disallow further caching
  # warn -- only log a warning
  policy: lru

# Authentication tokens
# Create with lorebox -gen-token
# id and hash must be set for each entry. Default level is assumed to be
# "fetch". level may be either "admin", "push", or "fetch"
# * "fetch" users may trigger a remote repository fetch
# * "push" users may trigger a remote repository fetch, create, delete, hide,
#   unhide, push self-hosted repos in their directory (/~/<id>/<repo>)
# * "admin" users can also use api for remote control of the box, control
#   anyone's self-hosted repos
tokens:
  - id: "bob"
    hash: "X5QT5_TQ1I6rOg2zbESyoUgjrk8bGMy4jJcYz9ISyPWS9kGLWDHPQIoweFvGeazAsw1yKHoddYcKss70HYOY0w"
    level: "admin"

# Enable pushing, creating and deleting self-hosted repositories
# Default is false
push: false

# We sit behind Caddy, so no need to do this
#
# Certificate and key to use for HTTPS. Obtain them from a provider like
# Letsencrypt, etc. Please use absolute paths here for predictable behaviour
# independent from the location you run the binary from
# https:
#  certificate: "cert.pem"
#  key: "key.pem"
